---
name: Python Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pytest coverage

      - name: Run tests with coverage
        run: |
          PYTHONPATH=runtime-protection coverage run -m pytest -vv
          coverage report -m
